LogLevel: warning # Log level: debug, info, warn, error, fatal, panic
Internal: 300 # Time to check the node connection (unit: second)
Timeout: 15 # Timeout for the tcp request (unit: second)
Concurrent: 20 # Max concurrent on nodes check

DDNS:
  Enable: true
  Provider: cloudflare
  Config:
    CLOUDFLARE_EMAIL: test@test.com
    CLOUDFLARE_API_KEY: YOUR_TOKEN
#  Provider: google
#  Config:
#    GOOGLEDOMAIN_USERNAME: username
#    GOOGLEDOMAIN_PASSWORD: password

Notify:
  Enable: false
  Provider: pushplus
  Config:
    PUSHPLUS_TOKEN: YOUR_TOKEN
#  Provider: telegram
#  Config:
#    TELEGRAM_APIHOST: PROXY.YOUR_DOMIAN.COM
#    TELEGRAM_CHATID: 123
#    TELEGRAM_TOKEN: YOUR_TOKEN

Nodes:
  - AccessKeyID: YOUR_AWS_AccessKeyID
    SecretAccessKey: YOUR_AWS_SecretAccessKey
    Region: ap-northeast-1 # AWS service endpoints, check https://docs.aws.amazon.com/general/latest/gr/rande.html for help
    InstanceName: Debian-1
    Network: [tcp4] # The type of network (tcp4, tcp6)
    Domain: node1.test.com # The node domain
    Port: 8080 # The node port

  - AccessKeyID: YOUR_AWS_AccessKeyID
    SecretAccessKey: YOUR_AWS_SecretAccessKey
    Region: ap-northeast-1 # AWS service endpoints, check https://docs.aws.amazon.com/general/latest/gr/rande.html for help
    InstanceName: Debian-1
    Network: [tcp4, tcp6] # The type of network (tcp4, tcp6)
    Domain: node2.test.com # The node domain
    Port: 8080 # The node port
